apiVersion: v1
kind: ConfigMap
metadata:
  name: temporal-worker-config
  namespace: temporal-system
  labels:
    app: temporal-worker
    component: configuration
data:
  # Application configuration
  application.yaml: |
    server:
      port: 8080
    
    spring:
      profiles:
        active: kubernetes
      application:
        name: temporal-worker
    
    logging:
      level:
        root: INFO
        io.temporal: DEBUG
        com.temporal: DEBUG
      pattern:
        console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    
    management:
      endpoints:
        web:
          exposure:
            include: health,info,metrics,prometheus
      endpoint:
        health:
          show-details: always
      metrics:
        export:
          prometheus:
            enabled: true

  # Temporal client configuration
  temporal.properties: |
    temporal.frontend.address=temporal-service:7233
    temporal.namespace=default
    temporal.worker.task-queue=default-task-queue
    temporal.worker.max-concurrent-activities=10
    temporal.worker.max-concurrent-workflows=5
    temporal.worker.max-concurrent-local-activities=10 