apiVersion: v1
kind: Secret
metadata:
  name: temporal-worker-secrets
  namespace: temporal-system
  labels:
    app: temporal-worker
    component: secrets
type: Opaque
data:
  # Database credentials (base64 encoded)
  # Example values - replace with actual base64 encoded values in production
  database-username: dGVtcG9yYWw=  # temporal
  database-password: dGVtcG9yYWw=  # temporal
  
  # API keys for external services (base64 encoded)
  external-api-key: eW91ci1hcGkta2V5LWhlcmU=  # your-api-key-here
  
  # JWT signing key for authentication (base64 encoded)
  jwt-secret: c3VwZXItc2VjdXJlLWp3dC1zaWduaW5nLWtleQ==  # super-secure-jwt-signing-key
stringData:
  # You can also use stringData for non-base64 encoded values
  # These will be automatically base64 encoded by Kubernetes
  external-service-url: "https://api.external-service.com"
  redis-connection-string: "redis://redis-service:6379" 