version: '3.8'

services:
  # TODO: Add Temporal server configuration
  # temporal:
  #   image: temporalio/auto-setup:1.22.0
  #   ports:
  #     - "7233:7233"
  #     - "8080:8080"
  #   environment:
  #     - DB=postgresql
  #     - DB_PORT=5432
  #     - POSTGRES_USER=temporal
  #     - POSTGRES_PWD=temporal
  #     - POSTGRES_SEEDS=postgresql
  #   volumes:
  #     - ./dynamicconfig:/etc/temporal/config/dynamicconfig
  #   depends_on:
  #     - postgresql

  # TODO: Add PostgreSQL database for Temporal
  # postgresql:
  #   image: postgres:13
  #   environment:
  #     POSTGRES_PASSWORD: temporal
  #     POSTGRES_USER: temporal
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data

  # TODO: Add your Kotlin Spring Boot application
  # temporal-worker:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   environment:
  #     - TEMPORAL_FRONTEND_ADDRESS=temporal:7233
  #     - SPRING_PROFILES_ACTIVE=docker
  #   depends_on:
  #     - temporal

  # TODO: Add Temporal Web UI (optional)
  # temporal-web:
  #   image: temporalio/web:1.15.0
  #   environment:
  #     - TEMPORAL_GRPC_ENDPOINT=temporal:7233
  #   ports:
  #     - "8088:8088"

# TODO: Add volume definitions
# volumes:
#   postgres_data:

# TODO: Add network configuration if needed
# networks:
#   temporal-network:
#     driver: bridge 