# TODO: Choose appropriate base image for Kotlin/Java application
# FROM openjdk:17-jre-slim

# TODO: Set working directory
# WORKDIR /app

# TODO: Copy and configure Gradle wrapper (for build)
# COPY gradlew .
# COPY gradle gradle/
# COPY build.gradle.kts .
# COPY settings.gradle.kts .

# TODO: Copy source code
# COPY src src/

# TODO: Build the application
# RUN ./gradlew build -x test

# TODO: Expose the application port
# EXPOSE 8080

# TODO: Set the entry point
# ENTRYPOINT ["java", "-jar", "build/libs/temporal-starter-0.0.1-SNAPSHOT.jar"]

# Hint: You might want to use multi-stage build for smaller image size
# FROM gradle:7.6-jdk17 AS build
# ... build stage ...
# FROM openjdk:17-jre-slim AS runtime
# ... runtime stage ... 